server:
  port: 7090
spring:
  elasticsearch:
    uris: http://localhost:9200
  rabbitmq:
    host: localhost
    port: 5672
    username: mustafa
    password: 123
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: elastic-service
rabbitmq:
  register-elastic-queue: registerElasticQueue


logging:
  level:
    root: info
  file:
    name: elastic.log
  logback:
    rollingpolicy:
      max-file-size: 100MB