server:
  port: 7072

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: mustafa
    password: 123
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5959/userDb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: ${java9secretkey}
  issuer:  ${java9issuer}
  audience: ${java9audience}
rabbitmq:
  register-queue: registerQueue
  activation-queue: activationQueue
  register-elastic-queue: registerElasticQueue
  register-elastic-binding: registerElasticBindingKey
  user-exchange: exchangeUser

redis:
  host: localhost
  port:  6379

