server:
  port: 7072

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5959/userDb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: ${java9secretkey}
  issuer:  ${java9issuer}
  audience: ${java9audience}


