server:
  port: 7072

spring:
  data:
    mongodb:
      host: localhost
      port: 27020
      username: java9user
      password: root
      database: userDb
  rabbitmq:
    host: localhost
    port: 5672
    username: mustafa
    password: 123
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service



jwt:
  secretKey: ${java9secretkey}
  issuer:  ${java9issuer}
  audience: ${java9audience}
rabbitmq:
  register-queue: registerQueue
  activation-queue: activationQueue
  register-elastic-queue: registerElasticQueue
  register-elastic-binding: registerElasticBindingKey
  user-exchange: exchangeUser

redis:
  host: localhost
  port:  6379
feign:
  auth: http://localhost:7071/api/v1/auth
